export enum SpecialKeys {
    Backspace = 'Backspace',
    Shift = 'Shift',
    CapsLock = 'CapsLock',
    Space = ' ',
    Ctrl = 'Control',
    ArrowLeft = 'ArrowLeft',
    ArrowRight = 'ArrowRight',
    Home = 'Home',
    End = 'End',
    // common punctuation keys
    Period = '.',
    Comma = ',',
    Exclamation = '!',
    Question = '?',
    Semicolon = ';',
    Colon = ':',
    Apostrophe = "'",
    Quote = '"',
    Hyphen = '-',
    Underscore = '_',
    Plus = '+',
    Equals = '=',
    LeftBracket = '[',
    RightBracket = ']',
    LeftBrace = '{',
    RightBrace = '}',
    Backslash = '\\',
    Pipe = '|',
    LessThan = '<',
    GreaterThan = '>',
    ForwardSlash = '/',
    Backtick = '`',
    Tilde = '~',
    At = '@',
    Hash = '#',
    Dollar = '$',
    Percent = '%',
    Caret = '^',
    Ampersand = '&',
    Asterisk = '*',
    LeftParen = '(',
    RightParen = ')'
}

// export const AllowedKeys = [
//   SpecialKeys.Backspace,
//   SpecialKeys.Shift,
//   SpecialKeys.CapsLock,
//   SpecialKeys.Space,
//   SpecialKeys.Ctrl,
//   SpecialKeys.ArrowLeft,
//   SpecialKeys.ArrowRight,
//   SpecialKeys.Home,
//   SpecialKeys.End,
// ];
